src/commands/General/ping.ts
src/lib/BediEmbed.ts

*Testing harness not yet created. Also it's a ping command...*
Generic ping command
- BediEmbed object for use in future commands
- Ping command now uses embeds

Ping Command Update

---

src/commands/Misc/github.ts

Issue Number: #6 
- GitHub Command provides link to this repository

Create Github Command

---

src/commands/Admin/settings.ts
src/tests/utils/settingsUtil.test.ts
src/utils/settingsUtil.ts

Switch case has no default branch.
validateModule function was unnecessary.
- Removed unnecessary functino.
- Added default branch to switch case
-

Sahils Fixes <3

---

package-lock.json
package.json
src/database/connectDatabase.ts
src/index.ts
src/listeners/ready.ts
src/utils/loggerUtil.ts

Issue Number: Closes #28 
- Implemented Winston Logger
Tests not created due to the nature of this PR

Implement Winston Logging Library

---

.github/workflows/main.yml

Issue Number: #39 
- Tests will only run on PR (As changes to main can only be made through PR, everything still must be tested before being merged)

Update Tests to only run on PR

---

src/preconditions/AdminOnly.ts
src/preconditions/BotOwnerOnly.ts

Issue Number: Closes #44 
- BotOwner Precondition checks for bot owner
- Stopped exporting preconditions as default (unnecessary0

Updating Preconditions

---

package.json
scripts/run.sh
scripts/test.sh
src/index.ts

Add in run script and modify index to no longer require inital .env

---

src/config.ts
src/index.ts
src/utils/discordUtil.ts

Issue Number: Closes #46 
- Moved Client Options to a config file

Added config

---

src/commands/Admin/purge.ts
src/preconditions/ManageChannelPerms.ts
src/utils/discordUtil.ts

Adding in a purge command
-
-
-

Purge command

---

src/commands/Admin/purge.ts
src/listeners/commandDenied.ts
src/listeners/commandError.ts
src/preconditions/AdminPerms.ts
src/preconditions/ManageChannelPerms.ts
src/preconditions/ManageMessagePerms.ts
src/utils/discordUtil.ts

Purge command dies with missing permissions.
- Fixed permissions preconditions and made purge command require correct permissions

Fix Permissions Preconditions

---

src/commands/Admin/purge.ts
src/commands/Admin/settings.ts
src/commands/General/ping.ts
src/commands/Verification/adminVerify.ts
src/commands/Verification/confirm.ts
src/commands/Verification/unverify.ts
src/commands/Verification/verify.ts
src/config.ts
src/database/models/SettingsModel.ts
src/listeners/commandDenied.ts
src/listeners/reactionPin.ts
src/listeners/reactionUnpin.ts

Issue Number: Closes #20 
- Reacting and unreacting with pushpin emoji pins/unpins the message

Add Reaction Pinning

---

src/commands/Admin/say.ts

Say command

---

src/commands/Admin/purge.ts
src/commands/Admin/say.ts
src/commands/Admin/settings.ts
src/commands/Quotes/addQuote.ts
src/commands/Verification/adminVerify.ts
src/commands/Verification/confirm.ts
src/commands/Verification/unverify.ts
src/commands/Verification/verify.ts
src/preconditions/QuotesEnabled.ts
src/preconditions/UserVerified.ts
src/preconditions/VerificationEnabled.ts

Issue Number: Closes #61 
- Checking a module is enabled or a user is verified is now a precondition
NOTE: For guild only commands, ensure that the first precondition in the array is the Guild Only Precondition, to ensure expected functionality.

Changed repetitive checks to preconditions

---

src/commands/Quotes/removeQuote.ts
src/database/models/QuoteModel.ts

Issue Number: Closes #56 
- Added remove quote command

Add RemoveQuote

---

src/commands/Admin/purge.ts
src/commands/Quotes/addQuote.ts
src/commands/Quotes/removeQuote.ts

Fixing Command Names

---

src/commands/Quotes/getRandomQuote.ts
src/database/models/QuoteModel.ts

Issue Number: Closes #58 
- Added Get Random Quote Command

Get random quote

---

package-lock.json
package.json
src/commands/Quotes/addQuote.ts
src/commands/Quotes/getQuotes.ts
src/database/models/QuoteModel.ts
src/tests/database/QuoteModel.test.ts

Issue Number: Closes #57 
- Added get quote command

Added Get Quotes Command

---

.github/workflows/main.yml
README.md
package.json
scripts/run.sh
scripts/test.sh
src/index.ts

This script setup will make production easier to setup

Updating scripts

---

src/commands/Birthdays/setBirthday.ts
src/database/models/BirthdayModel.ts
src/database/models/VerifiedUserModel.ts
src/tests/database/BirthdayModel.test.ts

Issue Number: Closes #18 
- Added set birthday command
Although we originally discussed having birthdays as a field on a VerifiedUser, I found that this wouldn't work well with our DB structure. Feel free to ask me for more details.

Add set birthday command

---

src/commands/Admin/morningAnnouncement.ts
src/commands/Admin/morningAnnouncementStop.ts
src/tests/utils/schedulerUtil.test.ts
src/utils/discordUtil.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #81 
- Add morning announcement functionality

Add morning announcement command

---

src/commands/Admin/birthdayAnnouncement.ts
src/commands/Admin/birthdayAnnouncementStop.ts
src/database/models/BirthdayModel.ts
src/tests/database/BirthdayModel.test.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #80 
- Added birthday announcements

Add birthday announcements

---

src/commands/Quotes/addQuote.ts
src/commands/Quotes/getQuotes.ts

Tiny change closes #87 and #84 and #82

Update addQuote and getQuotes

---

src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #77 
- If a quote doesn't have an associated date, various commands will act accordingly

Handle if document doesnt have date

---

src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts
src/database/models/QuoteModel.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #99 
- Added get all quotes command
Review after #100 is merged

Getallquotes

---

package-lock.json
package.json
src/commands/Admin/birthdayAnnouncement.ts
src/commands/Admin/lockdown.ts
src/commands/Admin/morningAnnouncement.ts

Issue Number: Closes #95  
- Scheduling system factors in the timezone of the guild

Updated scheduled stuff to actually use the timezone of the guild

---

src/index.ts
src/utils/discordUtil.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #107  Closes #118
- Removes repeating jobs if they fail
- Stop exporting client (bad practice)
-

Remove jobs on fail and stop exporting client

---

src/utils/schedulerUtil.ts

Issue Number: Closes #109 
- Doesn't repetitively log INFO on useless messages. Moved them to verbose
-
-

Change logs

---

README.md
src/lib/BediEmbed.ts

Update BediEmbed and ReadME

---

src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getRandomQuote.ts
src/database/models/QuoteModel.ts
src/tests/database/QuoteModel.test.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #117 
- Changed the author field in quote model to be called name (this matches prev DB structure more)
-
-

Change author field to name

---

src/commands/Admin/lockdown.ts
src/commands/Admin/morningAnnouncement.ts
src/commands/Admin/morningAnnouncementStop.ts
src/commands/Admin/purge.ts
src/commands/Admin/say.ts
src/commands/Admin/unlock.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/Birthdays/birthdayAnnouncementStop.ts
src/commands/Birthdays/getBirthdays.ts
src/commands/Birthdays/setBirthday.ts
src/commands/DueDates/addDueDate.ts
src/commands/DueDates/displayDueDates.ts
src/commands/General/github.ts
src/commands/General/ping.ts
src/commands/General/stats.ts
src/commands/Quotes/addQuote.ts
src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts
src/commands/Quotes/removeQuote.ts
src/commands/Settings/settings.ts
src/commands/Settings/toggleModule.ts
src/commands/Verification/adminVerify.ts
src/commands/Verification/confirm.ts
src/commands/Verification/unverify.ts
src/commands/Verification/verify.ts

Issue Number: closes #73 closes #108 
- Added detailed descriptions
- Reorganized command structure
-

Adding Detailed Descriptions and Reorganizing Command Structure

---

scripts/run.sh
scripts/test.sh

Add in npm install onto run and test script

---

src/commands/Admin/purge.ts
src/commands/Settings/setApprovals.ts
src/commands/Settings/setCategories.ts
src/commands/Settings/setCourses.ts
src/commands/Settings/setPinEmoji.ts
src/commands/Settings/setPrefix.ts
src/commands/Settings/setTimezone.ts
src/commands/Settings/setTypes.ts
src/commands/Settings/setVerifiedRole.ts

Issue Number: Closes #41 
- Added various commands to change guild settings

Add settings changing commands

---

src/database/models/BirthdayModel.ts
src/database/models/DueDateModel.ts
src/database/models/PendingVerificationuserModel.ts
src/database/models/QuoteModel.ts
src/database/models/SettingsModel.ts
src/database/models/VerifiedUserModel.ts
src/tests/database/PendingVerificationModel.test.ts
src/tests/database/QuoteModel.test.ts
src/utils/databaseUtil.ts

Issue Number: Closes #60 
- Makes model fields required and disables version key (unnecessary for our uses)
-
-

Makes model fields required and disables version key (unnecessary for our uses)

---

src/commands/DueDates/addDueDate.ts
src/commands/DueDates/removeDueDate.ts
src/database/models/DueDateModel.ts
src/preconditions/DueDatesSetup.ts

Issue Number: Closes #123 
- Added remove due date command
- Some minor fixes to the add due date command

Add remove due date

---

src/commands/Quotes/addQuote.ts
src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts

Issue Number: Closes #114 Closes #115
- Quote Commands cant possibly go over embed char limit
- Don't surround quotes in back ticks if they contain a mention

Fix Quote Edge Cases

---

src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/Birthdays/getBirthdays.ts
src/commands/Settings/setTimezone.ts
src/commands/Settings/toggleModule.ts

These are just small fixes to aliases or descriptions

Miscellaneous fixes to commands

---

src/commands/Settings/settings.ts

Update settings embed to include help and togglemodules command

---

src/commands/Admin/lockdown.ts
src/commands/Admin/morningAnnouncement.ts
src/commands/Admin/morningAnnouncementStop.ts
src/commands/Admin/purge.ts
src/commands/Admin/say.ts
src/commands/Admin/unlock.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/Birthdays/birthdayAnnouncementStop.ts
src/commands/DueDates/displayDueDates.ts
src/commands/Quotes/removeQuote.ts
src/commands/Settings/setApprovals.ts
src/commands/Settings/setCategories.ts
src/commands/Settings/setCourses.ts
src/commands/Settings/setPinEmoji.ts
src/commands/Settings/setPrefix.ts
src/commands/Settings/setTimezone.ts
src/commands/Settings/setTypes.ts
src/commands/Settings/setVerifiedRole.ts
src/commands/Settings/settings.ts
src/commands/Settings/toggleModule.ts
src/commands/Verification/adminVerify.ts

Fix preconditions

---

src/commands/Admin/morningAnnouncement.ts
src/commands/Admin/purge.ts
src/commands/Admin/say.ts
src/commands/Admin/unlock.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/General/help.ts
src/commands/Quotes/getRandomQuote.ts
src/commands/Settings/settings.ts

Fixing help

---

src/listeners/commandError.ts
src/utils/emailUtil.ts

Will log the entire message so we can view the context behind errors
-
-
-

Update logging properties for debugging

---

src/commands/Admin/purge.ts

update minor stuff in purge

---

src/commands/Admin/lockdown.ts

Lockdown properly considers timezone now

Lockdown Timezone Fix

---

src/commands/Quotes/addQuote.ts
src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts

Made all quotes command consider timezone
Closes #144

Quotes Timezone Fix

---

src/commands/Quotes/getAllQuotes.ts

Get all quotes UI fix

---

src/commands/Birthdays/birthdayAnnouncement.ts

Birthday Announcement Role Fix

---

src/commands/Birthdays/setBirthday.ts
src/commands/General/help.ts

This was causing an error if u DM'd the bot with $help for example

Commands that aren't guild only should not be accessing settingsData

---

src/commands/Admin/purge.ts
src/utils/discordUtil.ts

minor changes to purge

---

src/commands/Admin/lockdown.ts
src/utils/schedulerUtil.ts

Fixing Regex expressions and ensuring durations aren't evaluated as instant for scheduling

---

src/commands/Admin/morningAnnouncement.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/utils/schedulerUtil.ts

Issue Number: Closes #166 
-
-
-

Optional Auto Delete Option for Announcements

---

confirmTemplate.html
package-lock.json
package.json
src/commands/Verification/verify.ts
src/utils/emailUtil.ts

Issue Number: Closes #40 
- Email function uses an email template now that looks much nicer
-
-

Add HTML template for Confirmation Email

---

src/listeners/commandDenied.ts

Change command denied log level to DEBUG

---

src/commands/Birthdays/setBirthday.ts
src/commands/General/help.ts
src/utils/discordUtil.ts

Update fetchPrefix so that DMs can use no prefix as well

---

src/utils/schedulerUtil.ts

Scheduled unlock will still work even if the invoking message is deleted

---

src/index.ts
src/tests/utils/envUtil.test.ts
src/utils/envUtil.ts
src/utils/loggerUtil.ts

Update logger util stuff, make it into an env field

---

src/commands/Quotes/addQuote.ts

Addquote fixes

---

src/commands/Admin/purge.ts
src/utils/discordUtil.ts

Purge fixes 3

---

src/listeners/mentionPrefixOnly.ts

- Not Applicable
Issue Number: Closes #189 
- If you mention the bot without a command, it will tell you to run help

Add in mention prefix only listener

---

src/utils/schedulerUtil.ts

Previous implementation would not actually delete it if there were no birthdays the next day.

Ensure birthday announcement is auto deleted

---

src/utils/settingsUtil.ts

Add Due Dates to list of modules

---

src/commands/Quotes/getRandomQuote.ts

Fix Indent Issue on get random quote

---

src/commands/Admin/lockdown.ts
src/commands/Admin/morningAnnouncement.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/DueDates/addDueDate.ts
src/commands/DueDates/removeDueDate.ts
src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/commands/Quotes/getRandomQuote.ts
src/commands/Quotes/removeQuote.ts
src/utils/schedulerUtil.ts

Change timestamps

---

src/commands/Quotes/addQuote.ts

Change addquote to use message collectors instead

---

src/commands/Quotes/getRandomQuote.ts
src/database/models/QuoteModel.ts
src/utils/schedulerUtil.ts

Get Random Quote was not filtering by guild ID, now its fixed.

Fixing issue in getRandomQuote function

---

src/commands/Admin/morningAnnouncement.ts
src/commands/Birthdays/birthdayAnnouncement.ts
src/commands/DueDates/addDueDate.ts
src/commands/DueDates/removeDueDate.ts
src/commands/Quotes/addQuote.ts
src/commands/Settings/toggleModule.ts

Add catch statement to collector's end events

---

src/utils/discordUtil.ts

Fixing Purge to work in Threads

---

src/commands/Birthdays/getBirthdays.ts
src/database/models/BirthdayModel.ts

GetBirthdays without a month will show all birthdays

---

src/commands/General/help.ts
src/commands/Owner/guilds.ts

Adds a Owner only command to list all the guilds the bot is in

Add guilds command

---

src/commands/General/invite.ts

Add in invite command

---

src/utils/schedulerUtil.ts

Fixes a small issue where the morning announcement message looks wonky if there are no quotes saved in the server.

Fix issue in announcement when no quotes

---

src/commands/Owner/guilds.ts
src/utils/schedulerUtil.ts

Also includes guild ID in $guilds command for comparison with job error logs.

Include more information with job error log

---

src/utils/schedulerUtil.ts

Updating fail logs for Jobs

---

src/commands/Quotes/addQuote.ts
src/commands/Quotes/getAllQuotes.ts
src/commands/Quotes/getQuotes.ts
src/config.ts

Fix Get Quotes issue with large quotes

Fix Get Quotes

---

src/commands/Quotes/addQuote.ts

Just changes the quote command timeout (makes it longer so quotes timeout less)

Change Quote Command Timeout

---

src/commands/Settings/setEmailDomain.ts

Add Set Email Domain Command
